### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by garyrob** [wborgeaud/rust-vdf#1]
Hi, you don't give a license for this code, which according to Claude.ai means the following. I'm interested in using it, but it looks like I can't.

Claude:

By default, if a project on GitHub does not include a license, it falls under exclusive copyright protection. This means that no one has permission to use, modify, or distribute the code without explicit permission from the copyright holder (the project creator).

This is often surprising to people, as it means that even though the code is publicly visible, others technically cannot legally:
- Copy or fork the code
- Modify the code
- Distribute the code
- Use the code commercially
- Include the code in other projects

**Comment by wborgeaud** [comment]
Added a license in d3fb200
